### ISSUE TITLE
Add Form-Level Validation to Login Screen

### ISSUE THREAD

**Issue by digitallawyer** [codexstanford/techlist-frontend-web#10]
As a user, 
When I go to https://law.haus/app/login/,
And I enter and submit wrong login credentials,
I do not get any feedback.

The console log shows that the wrong username or password was entered

The expected behavior is that I see an error message telling me that the login information that was entered is incorrect.

**Comment by medelman17** [comment]
@denvercoder -- please address. It looks like you'll need to catch the 'UserNotFoundException' being thrown when you enter bad creds. 

<img width="543" alt="Screen Shot 2019-06-28 at 10 05 30 AM" src="https://user-images.githubusercontent.com/14793389/60347849-498d9f00-998c-11e9-8016-32112101dc85.png">

**Comment by medelman17** [comment]
@denvercoder -- you noted you had a fix for this ready to be pushed last week?
