### ISSUE TITLE
User Account Creation & Profile Completion  

### ISSUE THREAD

**Issue by digitallawyer** [codexstanford/techlist-frontend-web#11]
As a user, I should be able to visit the TechIndex website. 

If I am in an unauthenticated state, a login button should appear in the top right corner of the header. Clicking the button should take me to the login screen. If I have already created an account, I should be able to login. If I have already created a personal profile and company profile, I should be redirected to my profile page. If I have not already created a personal profile I should be redirected to create a profile. If I have created a profile, I should be redirected to my personal profile. 

From the login screen, if I have not yet created an account, I should be able to click 'Sign Up Today' and begin the following account creation process. At the first step of the process, I should be able to create an account in AWS cognito and subsequently verify my account using the code I receive via text message. Once my account is confirmed with AWS, an account for me should be created in the TechIndex database via graphql. I should then be navigated to step 2. 

At Step 2, I should be able to create a personal profile. Once I submit my personal profile, I should be navigated to step 3. If, for whatever reason, I lose my authenticated state and try to access step 2 directly via its url, I should be redirected to the login screen. As noted above, once I log in, I should be redirected back to the beginning of step 2 (or wherever I was in the process). If I successfully complete step 2, I should be navigated to step 3. 

At Step 3, I should be able to create a company profile. Once I submit my company profile, I should be navigated to step 4. 

At Step 4, I should be able to review my personal and company profile data and accept terms and conditions. Once I accept terms and conditions, I should be navigated to my personal profile page. Once I accept terms and conditions, I should not be able to access the account creation flow in an authenticated state.

**Comment by medelman17** [comment]
Closed as subsumed by #83, #84, et al previous.
