### ISSUE TITLE
[BUG]: Company Create Preview Starts Too Small on Desktop

### ISSUE THREAD

**Issue by medelman17** [codexstanford/techlist-frontend-web#110]
![Screen Shot 2019-07-11 at 7.40.40 AM.png](https://images.zenhubusercontent.com/5b3901ae39d269093fff704c/25eac23c-870b-480d-ae25-7079f0f8dfe2)

**Comment by TerrellLinnell** [comment]
Closed in WIP: Fix/company create polishing #123
