### ISSUE TITLE
[ENHANCE]: Make Company Create Registration Dialog Wider on Desktop

### ISSUE THREAD

**Issue by medelman17** [codexstanford/techlist-frontend-web#118]
Too much wasted real estate on Desktop.

 ![Screen Shot 2019-07-11 at 8.05.16 AM.png](https://images.zenhubusercontent.com/5b3901ae39d269093fff704c/e3cbf3b7-c8bc-4590-ba04-518099cbb829)

**Comment by denvercoder** [comment]
The version I have increases the width based on the content of the description.

So if you paste in 4 sentences it spans almost the entire width of the page.

**Comment by denvercoder** [comment]
I'll need to wait on this one until I can create a company.

**Comment by medelman17** [comment]
I don't think this requires needing to be able to create a company. The styling should be right regardless of whether the underlying functionality works, no? Also, I just pushed a fix. So it's moot. 

Good call with the extra widening bit. Please tackle that here, too. I'm guessing we'll just need to expand the max-width of the dialog and also ensure that the logo doesn't get crowded out.
