### ISSUE TITLE
[ENHANCE]: Make Front Page Images Display Nice-Like

### ISSUE THREAD

**Issue by medelman17** [codexstanford/techlist-frontend-web#121]
They're all blurry AF. We must be missing something here. 
<img width="454" alt="Screen Shot 2019-07-11 at 4 02 44 PM" src="https://user-images.githubusercontent.com/14793389/61081505-60ed7300-a3f5-11e9-80a6-f07f35be4d8b.png">

**Comment by denvercoder** [comment]
They're 100px images:

<img width="2755" alt="Screen Shot 2019-07-12 at 8 49 04 AM" src="https://user-images.githubusercontent.com/22165183/61137067-f59db280-a481-11e9-851c-2888989141cf.png">

**Comment by denvercoder** [comment]
The Bing News Search API returns a thumbnail image:

The imageUrl in this screenshot returns a 100x100 image.

Going to move on and return to this later.

<img width="1705" alt="Screen Shot 2019-07-12 at 9 10 58 AM" src="https://user-images.githubusercontent.com/22165183/61138661-23382b00-a485-11e9-9cd3-3f7dabd786a2.png">
