### ISSUE TITLE
[Bug]: Person Profile Create / Registration Should be on Paper/Card Component

### ISSUE THREAD

**Issue by medelman17** [codexstanford/techlist-frontend-web#128]
As a user, when I register for an account for the first time, the application thereafter asks me to fill in certain information about myself. I should be presented with a consistent experience for entering data across the application. Currently the profile create form is rendered directly on the background of the application, rather than on material's 'Paper' as all of our other registration/related forms are (see, e.g., screenshot of login screen below). This flow should conform to the rest. 
<img width="622" alt="Screen Shot 2019-07-12 at 8 37 27 AM" src="https://user-images.githubusercontent.com/14793389/61128670-90958d00-a480-11e9-9560-45df9ed8ccc5.png">

**Comment by denvercoder** [comment]
<img width="1066" alt="Screen Shot 2019-07-12 at 10 07 05 AM" src="https://user-images.githubusercontent.com/22165183/61142369-d2c4cb80-a48c-11e9-97e4-69c32b0ed403.png">
