### ISSUE TITLE
[Bug]: Company Preview Description Text Blows Up Page

### ISSUE THREAD

**Issue by medelman17** [codexstanford/techlist-frontend-web#153]
This should be addressable by constraining the size of the ListItemContents to a percentage of the ListItem parent and ensuring that the parent can't blow up the form? I'm not sure. Basically, the second content item should be set to take up as much room of the parent as is left. That way it can take up 100% when the logo is not there and whatever is left when it is. 

<img width="776" alt="Screen Shot 2019-07-15 at 6 23 31 PM" src="https://user-images.githubusercontent.com/14793389/61253040-ac718b00-a72d-11e9-8e9f-45f75deb9a5e.png">

**Comment by TerrellLinnell** [comment]
looks to be fixed already
