### ISSUE TITLE
Add 'Create Company' Button to User Profile Menu

### ISSUE THREAD

**Issue by medelman17** [codexstanford/techlist-frontend-web#32]
As a user, I should be able to initiate the 'create company' workflow from the navigation menu on my profile page. 

Replace 'Dashboard' with a button to the menu below that triggers the create company workflow. 

 ![Screen Shot 2019-07-01 at 8.13.34 AM.png](https://images.zenhubusercontent.com/5b3901ae39d269093fff704c/e211cb45-5286-44cd-8328-328d7a42d496)

**Comment by medelman17** [comment]
This button should simply navigate the user to `/app/company/`

**Comment by denvercoder** [comment]
Do we want to use the "Get Listed" button or add a new button? If we're adding a new button where would you like said button?

**Comment by denvercoder** [comment]
<img width="943" alt="Screen Shot 2019-07-02 at 10 28 36 AM" src="https://user-images.githubusercontent.com/22165183/60529601-2cbad980-9cb4-11e9-88bc-600ea3502b2f.png">
